name: Deploy Test HTML to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          find . -type f -exec curl -T {} -u $FTP_USERNAME:$FTP_PASSWORD ftp://$FTP_HOST/public_html/{} --ftp-create-dirs --ftp-ssl \;
