name: Deploy Test HTML to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Test FTP connection
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Test FTP connection and list files in public_html
          lftp -d -e "ls /public_html/; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST

      - name: Upload files to Hostinger via FTP with lftp
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Debug mode for more detailed output
          lftp -d -e "mirror -R --verbose --only-newer --delete-first ./ /public_html/; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
