name: Deploy Test HTML to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: spaction/ftp-upload-action@v1.0.0  # Node 16 compatible
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21  # Default FTP port, change if necessary
          localDir: ./  # Local directory or files to upload
          remoteDir: /public_html/  # Target directory on the server
