name: Deploy Test HTML to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: appleboy/ftp-action@v1.1.1  # Node 16 compatible
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Local directory or files to upload
          remote-dir: /public_html/  # Target directory on the server
          protocol: ftp  # Set protocol to ftp
