name: Deploy Test HTML to Hostinger

on:
  push:
    branches:
      - main  # Only trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0  # Use a specific version
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Specifies only the index.html file to upload
          server-dir: /public_html/  # Target directory on your Hostinger server
